mysite/home/home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
import os

urlpatterns = [
    path('', include('jobs.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/home/jobs/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.conf.urls import url
from django.views.static import serve
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

app_name='jobs'
urlpatterns = [
    path('', views.JobListView.as_view()),
    path('jobs', views.JobListView.as_view(), name='all'),
    path('job/<int:pk>', views.JobDetailView.as_view(), name='job_detail'),
    path('job/create',
        views.JobCreateView.as_view(success_url=reverse_lazy('jobs:all')), name='job_create'),
    path('job/<int:pk>/update',
        views.JobUpdateView.as_view(success_url=reverse_lazy('jobs:all')), name='job_update'),
    path('job/<int:pk>/delete',
        views.JobDeleteView.as_view(success_url=reverse_lazy('jobs:all')), name='job_delete'),
        
    path('employer/', views.EmployerListView.as_view(), name='employer_list'),
    path('employer/create/', views.EmployerCreateView.as_view(), name='employer_create'),
    path('employer/<int:pk>/update/', views.EmployerUpdateView.as_view(), name='employer_update'),
    path('employer/<int:pk>/delete/', views.EmployerDeleteView.as_view(), name='employer_delete'),
    # path('title/', views.EmployerListView.as_view(), name='title_list'),
    # path('title/create/', views.EmployerCreateView.as_view(), name='title_create'),
    # path('title/<int:pk>/update/', views.EmployerUpdateView.as_view(), name='title_update'),
    # path('title/<int:pk>/delete/', views.EmployerDeleteView.as_view(), name='title_delete'),
    path('location/', views.EmployerListView.as_view(), name='location_list'),
    path('location/create/', views.EmployerCreateView.as_view(), name='location_create'),
    path('location/<int:pk>/update/', views.EmployerUpdateView.as_view(), name='location_update'),
    path('location/<int:pk>/delete/', views.EmployerDeleteView.as_view(), name='location_delete'),

    # path('job_picture/<int:pk>', views.stream_file, name='job_picture'),
    path('job/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='job_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('jobs:all')), name='job_comment_delete'),
    path('job/<int:pk>/favorite',
       views.JobdFavoriteView.as_view(), name='job_favorite'),
    path('job/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='job_unfavorite'),


    url(r'^static/(?P<path>.*)$', serve,
    {'document_root': os.path.join(BASE_DIR, 'static'), 'show_indexes': True},
    name='static'
)
]

mysite/home/jobs/forms.py
from django import forms
from .models import Job, Employer,Location
from django.core.files.uploadedfile import InMemoryUploadedFile
from .humanize import naturalsize


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    # picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    # upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the jobs application :)
    class Meta:
        model = Job
        fields = ['title', 'employer', 'location', 'salary_l', 'salary_h','description']  # Picture is manual

    # # Validate the size of the picture
    # def clean(self):
    #     cleaned_data = super().clean()
    #     pic = cleaned_data.get('picture')
    #     if pic is None:
    #         return
    #     if len(pic) > self.max_uplojob_limit:
    #         self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # # Convert uploaded File object to a picture
    # def save(self, commit=True):
    #     instance = super(CreateForm, self).save(commit=False)

    #     # We only need to adjust picture if it is a freshly uploaded file
    #     f = instance.picture   # Make a copy
    #     if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
    #         bytearr = f.read()
    #         instance.content_type = f.content_type
    #         instance.picture = bytearr  # Overwrite with the actual image data

    #     if commit:
    #         instance.save()

        # return instance


class EmployerForm(forms.ModelForm):
    class Meta:
        model=Employer
        fields=['name','description']
class LocationForm(forms.ModelForm):
    class Meta:
        model=Location
        fields=['name']
# class TitleForm(forms.ModelForm):
#     class Meta:
#         model=Title
#         fields=['name','description']
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

mysite/home/jobs/views.py
from django.shortcuts import render
from django.views import View
from django.urls import reverse_lazy,reverse
from .models import Job,Comment, Fav, Employer,Location
from .owner import OwnerListView,OwnerDetailView,OwnerCreateView,OwnerUpdateView,OwnerDeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CreateForm,CommentForm,EmployerForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.humanize.templatetags.humanize import naturaltime
from .utils import dump_queries
from django.db.models import Q

class JobListView(OwnerListView):
    model = Job
    template_name = "jobs/job_list.html"

    def get(self, request) :
        strval =  request.GET.get("search", False)
        if strval :
            query = Q(title__contains=strval)
            query.add(Q(employer__name__contains=strval), Q.OR)
            query.add(Q(location__name__contains=strval), Q.OR)
            query.add(Q(description__contains=strval), Q.OR)
            job_list = Job.objects.filter(query).select_related().order_by('-updated_at')[:10] 
        else :
            job_list = Job.objects.all().order_by('-updated_at')[:10]
        employ_count =Employer.objects.all().count()
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_jobs.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]
        # Augment the job_list
        for obj in job_list:
            obj.natural_updated = naturaltime(obj.updated_at)         
        ctx = {'job_list' : job_list, 'favorites': favorites,'employ_count':employ_count,'search':strval}
        dump_queries()
        return render(request, self.template_name, ctx)




class JobDetailView(OwnerDetailView):
    model = Job
    template_name = "jobs/job_detail.html"
    def get(self, request, pk) :
        x = Job.objects.get(id=pk)
        comments = Comment.objects.filter(job=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'job' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)




class JobCreateView(LoginRequiredMixin, View):
    template_name = 'jobs/job_form.html'
    success_url = reverse_lazy('jobs:all')
    model=Job

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        job = form.save(commit=False)
        job.owner = self.request.user
        job.save()
        return redirect(self.success_url)


class JobUpdateView(LoginRequiredMixin, View):
    template_name = 'jobs/job_form.html'
    success_url = reverse_lazy('jobs:all')

    def get(self, request, pk):
        job = get_object_or_404(Job, id=pk, owner=self.request.user)
        form = CreateForm(instance=job)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        job = get_object_or_404(Job, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=job)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        job = form.save(commit=False)
        job.save()

        return redirect(self.success_url)

class JobDeleteView(OwnerDeleteView):
    model = Job
    template_name = "jobs/job_confirm_delete.html"



class EmployerListView(OwnerListView):
    model = Employer
    template_name = "employers/employer_list.html"

    def get(self, request) :
        employer_list = Employer.objects.all()
        ctx = {'employer_list' : employer_list}
        return render(request, self.template_name, ctx)


class EmployerCreateView(LoginRequiredMixin, View):
    template_name = 'employers/employer_form.html'
    success_url = reverse_lazy('jobs:all')

    
    def get(self, request, pk=None):
        form = EmployerForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = EmployerForm(request.POST, request.FILES or None)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        employer = form.save(commit=False)
        employer.owner = self.request.user
        employer.save()
        return redirect(self.success_url)


class EmployerUpdateView(LoginRequiredMixin, View):
    template_name = 'employers/employer_form.html'
    success_url = reverse_lazy('jobs:all')

    def get(self, request, pk):
        employer = get_object_or_404(Employer, id=pk, owner=self.request.user)
        form = EmployerForm(instance=employer)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        employer = get_object_or_404(Employer, id=pk, owner=self.request.user)
        form = EmployerForm(request.POST, request.FILES or None, instance=employer)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        employer = form.save(commit=False)
        employer.save()

        return redirect(self.success_url)

class EmployerDeleteView(OwnerDeleteView):
    model = Employer
    template_name = "employers/employer_confirm_delete.html"
    success_url = reverse_lazy('jobs:all')




# class TitleListView(OwnerListView):
#     model = Title
#     template_name = "titles/title_list.html"

#     def get(self, request) :
#         title_list = Title.objects.all()
#         ctx = {'title_list' : title_list}
#         return render(request, self.template_name, ctx)


# class TitleCreateView(LoginRequiredMixin, View):
#     template_name = 'titles/title_form.html'
#     success_url = reverse_lazy('jobs:all')

    
#     def get(self, request, pk=None):
#         form = TitleForm()
#         ctx = {'form': form}
#         return render(request, self.template_name, ctx)

#     def post(self, request, pk=None):
#         form = TitleForm(request.POST, request.FILES or None)
#         if not form.is_valid():
#             ctx = {'form': form}
#             return render(request, self.template_name, ctx)

#         # Add owner to the model before saving
#         title = form.save(commit=False)
#         title.owner = self.request.user
#         title.save()
#         return redirect(self.success_url)


# class TitleUpdateView(LoginRequiredMixin, View):
#     template_name = 'titles/title_form.html'
#     success_url = reverse_lazy('jobs:all')

#     def get(self, request, pk):
#         title = get_object_or_404(Title, id=pk, owner=self.request.user)
#         form = TitleForm(instance=title)
#         ctx = {'form': form}
#         return render(request, self.template_name, ctx)

#     def post(self, request, pk=None):
#         title = get_object_or_404(Title, id=pk, owner=self.request.user)
#         form = TitleForm(request.POST, request.FILES or None, instance=title)

#         if not form.is_valid():
#             ctx = {'form': form}
#             return render(request, self.template_name, ctx)

#         title = form.save(commit=False)
#         title.save()

#         return redirect(self.success_url)

# class TitleDeleteView(OwnerDeleteView):
#     model = Title
#     template_name = "titles/title_confirm_delete.html"
#     success_url = reverse_lazy('jobs:all')


class LocationListView(OwnerListView):
    model = Location
    template_name = "locations/location_list.html"

    def get(self, request) :
        location_list = Location.objects.all()
        ctx = {'location_list' : location_list}
        return render(request, self.template_name, ctx)


class LocationCreateView(LoginRequiredMixin, View):
    template_name = 'locations/location_form.html'
    success_url = reverse_lazy('jobs:all')

    
    def get(self, request, pk=None):
        form = LocationForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = LocationForm(request.POST, request.FILES or None)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        location = form.save(commit=False)
        location.owner = self.request.user
        location.save()
        return redirect(self.success_url)


class LocationUpdateView(LoginRequiredMixin, View):
    template_name = 'locations/location_form.html'
    success_url = reverse_lazy('jobs:all')

    def get(self, request, pk):
        location = get_object_or_404(Location, id=pk, owner=self.request.user)
        form = LocationForm(instance=location)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        location = get_object_or_404(Location, id=pk, owner=self.request.user)
        form = LocationForm(request.POST, request.FILES or None, instance=location)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        location = form.save(commit=False)
        location.save()

        return redirect(self.success_url)

class LocationDeleteView(OwnerDeleteView):
    model = Location
    template_name = "locations/location_confirm_delete.html"
    success_url = reverse_lazy('jobs:all')

mysite/home/jobs/templates/jobs/comment_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'jobs:job_detail' comment.job.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

mysite/home/jobs/templates/jobs/job_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}

{% block head %}
<link rel="stylesheet" href="css/bootstrap.css">

{% endblock %}
<h1>Delete Job</h1>

<p>Are you sure you want to delete the job: {{ job }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

mysite/home/jobs/templates/jobs/job_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %}
<link rel="stylesheet" href="{% url 'jobs:static' 'bootstrap.css' %}">
<style>

.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}

</style>
{% endblock %}
{% block content %}
<span style="float: right;">
({{ job.updated_at|naturaltime }})
{% if job.owner == user %}
<a href="{% url 'jobs:job_update' job.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'jobs:job_delete' job.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h2>{{ job.title }}</h21>
<br>
<h4>Location: {{ job.location }}</h4>
<h4>Salary: ${{ job.salary_l }}k-{{ job.salary_h }}k</h4>
<h4 >Description</h4>
<div id='description' class='container'>
  <div class="row">
      <div class='col-lg-12' >
        <p>{{job.description|safe}}</p>
      </div>
  </div>
</div>

{% if job.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'jobs:job_picture' job.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ job.text }}

{% if user %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'jobs:job_comment_create' job.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All Jobs" onclick="window.location.href='{% url 'jobs:all' %}';return false;">
</form>
</p>
{% endif %}


{% for comment in comments %}
<p id='comment'> {{ comment.text }}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'jobs:job_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}
</p>

<p>
<a href="{% url 'jobs:all' %}">All jobs</a>
</p>
{% endblock %}

mysite/home/jobs/templates/jobs/job_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'jobs:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

mysite/home/jobs/templates/jobs/job_list.html
{% extends "base_menu.html" %}
{% block content %}
<header>
  <h1>Jobs</h1>
</header>
<div style="float:right">
  <!--https://www.w3schools.com/howto/howto_css_search_button.asp-->
 <form>
   <input type="text" placeholder="Search.." name="search"
   {% if search %} value="{{ search }}" {% endif %}
   >
   <button type="submit"><i class="fa fa-search"></i></button>
 <a href="{% url 'jobs:all' %}"><i class="fa fa-undo"></i></a>
 </form>
 </div>
<p>
{% if job_list %}
<ul>
  {% for job in job_list %}
    <li>
        <a href="{% url 'jobs:job_detail'  job.id %}">{{ job.title }}</a>
        {% if job.owner == user %}
        (<a href="{% url 'jobs:job_update' job.id %}">Edit</a> |
        <a href="{% url 'jobs:job_delete' job.id %}">Delete</a>)
        {% endif %}

        {% if user.is_authenticated %}
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#" onclick=
            "favPost('{% url 'jobs:job_unfavorite' job.id %}', {{ job.id }} );return false;"
            {% if job.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{job.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'jobs:job_favorite' job.id %}', {{ job.id }} );return false;"
            {% if job.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{job.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no jobs in the database.</p>
{% endif %}
</p>

<p>
  {% if employ_count > 0 %}
    <a href="{% url 'jobs:job_create' %}">Add a job</a>
  {% else %}
    Please add an employer before you add a job.
  {% endif %}
</p>
<p>
  <a href="{% url 'jobs:employer_list' %}">View employers</a> ({{ employer_count }}) |
  <a href="{% url 'jobs:employer_create' %}">Add a employer</a>
</p>
<p>
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'jobs:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'jobs:all' %}">Login</a>
{% endif %}
</p>
<script>
function favPost(url, job_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+job_id).toggle();
        $("#favorite_star_"+job_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}